name: VarietyLoot
main: VarietyMain.VarietyMain   # Ojo aquí: depende del package
version: 1.0.0
api-version: 1.16
author: TuNombre
description: Plugin VarietyLoot que añade un sistema de loot variado.

commands:
  varietyloot:
    description: Comando principal del complemento
    usage: /<command>
    permission: varietyloot.use
    permission-message: No tienes permiso para usar este comando.

permissions:
  varietyloot.use:
    description: Permite usar /loot
    default: op
