name: VarietyLoot
main: gc.grivyzom.VarietyMain
version: 1.0.0
api-version: 1.21
author: Brocolitx
description: Plugin VarietyLoot que añade un sistema de loot variado.

commands:
  varietyloot:
    description: Comando principal del complemento
    usage: /<command>
    permission: varietyloot.use
    permission-message: No tienes permiso para usar este comando.
    aliases: [vloot, loot]

permissions:
  varietyloot.use:
    description: Permite usar /varietyloot
    default: op
  varietyloot.reload:
    description: Permite recargar la configuración
    default: op
  varietyloot.give:
    description: Permite dar ítems personalizados
    default: op
  varietyloot.admin:
    description: Acceso completo al plugin
    default: op
    children:
      varietyloot.use: true
      varietyloot.reload: true
      varietyloot.give: true